config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	  resources :comments
  end
  root to: "posts#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@post = Post.find(params[:post_id])
  	@comment = Comment.new
  end

  def create
  	@post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:notice] = "Comment was saved."
      redirect_to @post
    else
      flash[:error] = "There was an error saving the comment. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    puts params
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params.require(:comment).permit(:body))
      flash[:notice] = "Comment was updated."
      redirect_to @post
    else
      flash[:error] = "There was an error saving the post. Please try again."
    end
  end

  def destroy
  	@post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:notice] = "Post was deleted."
      redirect_to @post
    else
      flash[:error] = "There was an error deleting the comment. Please try again."
      render :edit
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all

  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
  	@post = Post.find(params[:id])
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to @post
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params.require(:post).permit(:title, :body))
      flash[:notice] = "Post was updated."
      redirect_to @post
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post was deleted."
      redirect_to @post
    else
      flash[:error] = "There was an error deleting the post. Please try again."
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
  <div class="row">
  <div class="col-md-2"></div>
   <div class="col-md-8">
     <%= form_for [@post, @comment] do |f| %>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter comment body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
   <div class="col-md-12"></div>
 </div>

app/views/comments/new.html.erb
  <div class="row">
  <div class="col-md-2"></div>
   <div class="col-md-8">
     <%= form_for [@post, @comment] do |f| %>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter comment body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
   <div class="col-md-12"></div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>Career Plug</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to("CareerPlug", root_path, class: "navbar-brand") %>
    </div>

    <%= button_to 'Add Post', new_post_path, :class => 'btn btn-info navbar-btn btn-sm navbar-right', :method => :get  %>
  </div>
</nav>

 <div class="container">
    <%= yield %>

</div>
</html>

app/views/posts/edit.html.erb
  <div class="row">
  <div class="col-md-2"></div>
   <div class="col-md-8">
     <%= form_for @post do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
   <div class="col-md-12"></div>
 </div>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">

 	<% @posts.each do |post| %>
	    <div class="media">
	       <div class="media-body">
	       	<h2 class="media-heading"><%= truncate(post.title, :length => 40) %></h2>
	        <div class="media-body">
		       	<h5 class="media-heading"><%= truncate(post.body, :length =>200) %></h5>
	     	</div>
	     </div>
	   </div>
	   <br>
	   <div class="row">
		   <div class="col-md-6 text-left">
		    <a class="btn btn-info btn-circle text-uppercase btn-xs .inactiveLink" data-toggle="collapse" href=""><span class="glyphicon glyphicon-comment"></span> <%= post.comments.count %> comments</a>
		   </div>	   
		   <div class="col-md-6 text-right">
		   <%= link_to "Read More", post %>
		   </div>
		</div>
	   <hr>
	 <% end %>

	</div>
	<div class="col-md-2"></div>
</div>

app/views/posts/new.html.erb
  <div class="row">
  <div class="col-md-2"></div>
   <div class="col-md-8">
     <%= form_for @post do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
   <div class="col-md-12"></div>
 </div>

app/views/posts/show.html.erb
<div class="title">

<div>
	<h1><%= @post.title %></h1>
	<p><%= @post.body %></p>
	<%= link_to "Edit", edit_post_path(@post), class: 'btn btn-success btn-xs' %>
	<%= link_to "Delete", @post, method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure you want to delete this post?' } %> 
	</div>
</div>


<div class="row">
	<div class="col-sm-3"></div>

<div class="col-sm-1">
			<div class="thumbnail">
				<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
			</div>
		</div>

	<div class="col-sm-5">
			<div class="panel panel-default">
				<%= form_for [@post, @comment] do |f| %>
				<div class="panel-body">
				<%= f.text_area :body, rows: 4, class: 'form-control', placeholder: "Add comment body here" %>
				<%= f.submit "Save", class: 'btn btn-default btn-xs' %>

				</div>
				    <% end %>

			</div>
		</div>

	<div class="col-sm-3"></div>
</div>

<% @post.comments.each do |comment| %>
	<div class="row">
		<div class="col-sm-4"></div>
		<div class="col-sm-1">
			<div class="thumbnail">
				<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
			</div>
		</div>
		<div class="col-sm-3">
			<div class="panel panel-default">
				<div class="panel-heading">
				<strong>Tom</strong> <span class="text-muted">commented 5 days ago</span>
				</div>

				<div class="panel-body">
				<%= comment.body %>
		
				</div>
				<div class="panel-footer text-right">
					<%= link_to "Edit", edit_post_comment_path(@post, comment), class: 'btn btn-default btn-xs' %>
	    		<%= link_to "Delete", post_comment_path(@post, comment), method: :delete, class: 'btn btn-default btn-xs', data: { confirm: 'Are you sure you want to delete this comment?' } %> 
				</div>
			</div>
		</div>
		<div class="col-sm-4"></div>
	</div>
<% end %>

</div>